name: Build Electron Project for Windows

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm install

      - name: FFmpeg Download
        run: Invoke-WebRequest -Uri https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-lgpl.zip -Outfile FFmpeg.zip 

      - name: Python Embeddable Download
        run: Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.11.4/python-3.11.4-embed-amd64.zip -Outfile Python.zip

      - name: Whisper Models Download
        run: |
          Invoke-WebRequest -Uri https://openaipublic.azureedge.net/main/whisper/models/ed3a0b6b1c0edf879ad9b11b1af5a0e6ab5db9205f891f668f8b0e6c6326e34e/base.pt -OutFile .\src\AITranscribe\models\base.pt
          Invoke-WebRequest -Uri https://openaipublic.azureedge.net/main/whisper/models/9ecf779972d90ba49c06d968637d720dd632c55bbf19d441fb42bf17a411e794/small.pt -OutFile .\src\AITranscribe\models\small.pt

      - name: Setup dependencies
        run: |
          Expand-Archive .\FFmpeg.zip .\
          Copy-Item -path .\ffmpeg-master-latest-win64-lgpl\bin\ffmpeg.exe .\src\FFmpeg\
          Expand-Archive .\Python.zip -DestinationPath .\src\AITranscribe
          (Get-Content .\src\AITranscribe\Python311._pth) -replace '#import site', 'import site' | Set-Content .\src\AITranscribe\Python311._pth
          Invoke-WebRequest -Uri https://bootstrap.pypa.io/get-pip.py -Outfile .\src\AITranscribe\get-pip.py
          .\src\AITranscribe\Python.exe .\src\AITranscribe\get-pip.py
          .\src\AITranscribe\Python.exe -m pip install git+https://github.com/openai/whisper.git

      - name: Build Electron project for Windows
        run: npm run build_win

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: AITranscribe-Electron
          path: build/*.zip
          #path: build/win-unpacked/
