name: Build Electron Project for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron project for Windows
        run: npm run build_win

      - name: FFmpeg Download
        run: Invoke-WebRequest -Uri https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-lgpl.zip -Outfile FFmpeg.zip 

      - name: Python Embeddable Download
        run: Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.11.4/python-3.11.4-embed-amd64.zip -Outfile Python.zip

      - name: Setup dependencies
        shell: pwsh
        run: |
          Expand-Archive .\FFmpeg.zip -DestinationPath .\build\win-unpacked\resources\app\src\FFmpeg
          Expand-Archive .\Python.zip -DestinationPath .\build\win-unpacked\resources\app\src\AITranscribe

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: AITranscribe-Electron
          #Path: build/*.zip
          Path: build/win-unpacked/