name: Build Electron Project for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron project for Windows
        run: npm run build_win

      #- name: FFmpeg Download
      #  run: 

      #- name: Whisper Download
      #  run:

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-build
          #Path: build/*.zip
          Path: build/