name: Display Git Log

on:
  push:

jobs:
  display-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Display Git Log
        run: git log --graph